config/routes.rb
Rails.application.routes.draw do
  get 'search/create'
  get 'search/filter'
  scope 'secretaria' do
    resources :pensioners
  end
  scope 'integrador' do
    resources :pensioners
  end
  scope 'coordinador' do
    resources :pensioners
  end
  get 'pensioners/integrador'


  devise_for :users
  devise_scope :user do
    root 'devise/sessions#new'
  end
end

app/models/pensioner.rb
class Pensioner < ApplicationRecord
  has_attached_file :anexo1
  validates_attachment :anexo1, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo2
  validates_attachment :anexo2, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo3
  validates_attachment :anexo3, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo4
  validates_attachment :anexo4, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo5
  validates_attachment :anexo5, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo6
  validates_attachment :anexo6, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo7
  validates_attachment :anexo7, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo8
  validates_attachment :anexo8, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo9
  validates_attachment :anexo9, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo10
  validates_attachment :anexo10, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo11
  validates_attachment :anexo11, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo12
  validates_attachment :anexo12, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo13
  validates_attachment :anexo13, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo14
  validates_attachment :anexo14, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo15
  validates_attachment :anexo15, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo16
  validates_attachment :anexo16, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo17
  validates_attachment :anexo17, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  has_attached_file :anexo18
  validates_attachment :anexo18, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

  # validates :turno,:numero_correspondencia, :numero_oficio,:fecha_oficio, :fecha_recepcion,
  #   :promovente, :numero_juicio, :fecha_oficio, :turnado, :fecha_oficio, :anexo1, presence: true

  # validates :numero_juicio, :numero_oficio, uniqueness: true
  # validates :numero_pension, :numero_expediente, uniqueness: true

  # validates :numero_pension, :sala, :tipo_expediente, :numero_expediente, :estado_expediente, :letra, :termino,
  #  :envio_juridico, :monto_cheque, :ajuste_cuota, :clasificacion, presence: true




end

app/controllers/pensioners_controller.rb
class PensionersController < ApplicationController
  before_action :set_pensioner, only: [:show, :edit, :update, :destroy]

  # GET /pensioners
  # GET /pensioners.json
  def index
    @pensioners = Pensioner.all.paginate(page: params[:page], per_page: 10).order("created_at DESC")
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def integrador
  end
  # GET /pensioners/1
  # GET /pensioners/1.json
  def show
  end

  # GET /pensioners/new
  def new
    @pensioner = Pensioner.new
  end

  # GET /pensioners/1/edit
  def edit
  end

  # POST /pensioners
  # POST /pensioners.json
  def create
    @pensioner = Pensioner.new(pensioner_params)
      if @pensioner.save
        respond_to do |format|
        format.html { redirect_to @pensioner, notice: 'Pensioner was successfully created.' }
        format.json { render :show, status: :created, location: @pensioner }
      else
        format.html { render :new }
        format.json { render json: @pensioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pensioners/1
  # PATCH/PUT /pensioners/1.json
  def update
    respond_to do |format|
      if @pensioner.update(pensioner_params)
        if current_user.role == 'secretaria'
          format.html { redirect_to pensioners_path, notice: 'Pensioner was successfully updated.' }
          format.json { render :show, status: :ok, location: @pensioner }
        end
        if current_user.role == 'integrador' or current_user.role == 'coordinador'
          format.html { redirect_to @pensioner, notice: 'Pensioner was successfully updated.' }
          format.json { render :show, status: :ok, location: @pensioner }
        end
      else
        format.html { render :edit }
        format.json { render json: @pensioner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pensioners/1
  # DELETE /pensioners/1.json
  def destroy
    @pensioner.destroy
    respond_to do |format|
      format.html { redirect_to pensioners_url, notice: 'Pensioner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pensioner
    @pensioner = Pensioner.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pensioner_params
    params.require(:pensioner).permit(:turno, :numero_oficio, :fecha_oficio, :fecha_recepcion, :promovente, :numero_juicio, :turnado, :anexo1, :numero_correspondencia,
                                      :numero_pension, :tipo_expediente,
                                      :numero_expediente, :estatus_expediente,
                                      :observaciones, :clasificacion,
                                      :letra, :termino, :envio_juridico,
                                      :monto_cheque, :ajuste_cuota, :sala,
                                      :que_se_liquida, :fecha_liquidacion,
                                      :autoridad_cumplimiento, :materia,
                                      :fecha_uj, :numero_sp, :fecha_sp, :numero_uj,
                                      :fecha_sentencia, :integrador,
                                      :liquidador, :estado_final,
                                      :anexo2, :anexo3, :anexo4,
                                      :anexo5, :anexo6, :anexo7, :anexo8, :anexo9, :anexo10, :anexo11, :anexo12,:anexo13, :anexo14, :anexo15,:anexo16, :anexo17, :anexo18)
  end
end

app/helpers/pensioners_helper.rb
module PensionersHelper
end

app/views/pensioners/_pensioner.html.erb
<br>
<br>
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Turno</th>
      <th scope="col">Numero oficio</th>
      <th scope="col">Fecha oficio</th>
      <th scope="col">Fecha recepcion</th>
      <th scope="col">Nombre promovente</th>
      <th scope="col">Turnado</th>
      <th scope="col">Numero juicio</th>
      <th scope="col">Numero correspondencia</th>
      <th scope="col">Anexos</th>
      <% if current_user.role.include?('integrador') or current_user.role.include?('coordinador')%>
        <th scope="col">Numero pensión</th>
        <th scope="col">Sala</th>
        <th scope="col">Tipo expediente</th>
        <th scope="col">Numero expediente</th>
        <th scope="col">Observaciones</th>
        <th scope="col">Letra</th>
        <th scope="col">Termino de la sentencia</th>
        <th scope="col">Envio juridico</th>
        <th scope="col">Monto cheque</th>
        <th scope="col">Ajuste cuota</th>
        <th scope="col">Estatus del expediente</th>
        <th scope="col">Clasificación del expediente</th>
        <th scope="col">Anexos</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

    <tbody>
      <tr>
        <td><%= pensioner.turno %></td>
        <td><%= pensioner.numero_oficio %></td>
        <td><%= pensioner.fecha_oficio %></td>
        <td><%= pensioner.fecha_recepcion %></td>
        <td><%= pensioner.promovente %></td>
        <td><%= pensioner.turnado %></td>
        <td><%= pensioner.numero_juicio %></td>
        <td><%= pensioner.numero_correspondencia %></td>
        <% if pensioner.anexo1?%>
          <td><%= link_to pensioner.anexo1.original_filename, pensioner.anexo1.url, target: '_blank', id:'pdf-link' %></td>
          <% else %>
          <td></td>
        <% end %>
        <% if pensioner.anexo13?%>
          <td><%= link_to pensioner.anexo13.original_filename, pensioner.anexo13.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if pensioner.anexo14?%>
          <td><%= link_to pensioner.anexo14.original_filename, pensioner.anexo14.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if pensioner.anexo15?%>
          <td><%= link_to pensioner.anexo15.original_filename, pensioner.anexo15.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if pensioner.anexo16?%>
          <td><%= link_to pensioner.anexo16.original_filename, pensioner.anexo16.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if pensioner.anexo17?%>
          <td><%= link_to pensioner.anexo17.original_filename, pensioner.anexo17.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if pensioner.anexo18?%>
          <td><%= link_to pensioner.anexo18.original_filename, pensioner.anexo18.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if current_user.role.include?('secretaria')%>
          <td><%= link_to 'Editar', edit_pensioner_path(pensioner),class:'btn btn-danger text-white' %></td>
          <td><%= link_to 'Mostrar', pensioner_path(pensioner),class:'btn btn-secondary text-white' %></td>
        <% end %>
        <% if current_user.role.include?('integrador') or current_user.role.include?('coordinador')%>
          <td><%= pensioner.numero_pension %></td>
          <td><%= pensioner.sala %></td>
          <td><%= pensioner.tipo_expediente %></td>
          <td><%= pensioner.numero_expediente %></td>
          <td><%= pensioner.observaciones %></td>
          <td><%= pensioner.letra%></td>
          <td><%= pensioner.termino%></td>
          <td><%= pensioner.envio_juridico %></td>
          <td><%= pensioner.monto_cheque %></td>
          <td><%= pensioner.ajuste_cuota %></td>
          <td><%= pensioner.estatus_expediente%></td>
          <td><%= pensioner.clasificacion%></td>
          <% if pensioner.anexo2?%>
            <td><%= link_to pensioner.anexo2.original_filename, pensioner.anexo2.url, target: '_blank', id:'pdf-link' %></td>
            <% else %>
            <td></td>
          <% end %>
          <% if pensioner.anexo3?%>
            <td><%= link_to pensioner.anexo2.original_filename, pensioner.anexo2.url, target: '_blank', id:'pdf-link' %></td>
          <% end %>
          <% if pensioner.anexo4?%>
            <td><%= link_to pensioner.anexo2.original_filename, pensioner.anexo2.url, target: '_blank', id:'pdf-link' %></td>
          <% end %>
          <% if pensioner.anexo5?%>
            <td><%= link_to pensioner.anexo2.original_filename, pensioner.anexo2.url, target: '_blank', id:'pdf-link' %></td>
          <% end %>
          <% if pensioner.anexo6?%>
            <td><%= link_to pensioner.anexo2.original_filename, pensioner.anexo2.url, target: '_blank', id:'pdf-link' %></td>
          <% end %>
          <% if pensioner.anexo7?%>
            <td><%= link_to pensioner.anexo2.original_filename, pensioner.anexo2.url, target: '_blank', id:'pdf-link' %></td>
          <% end %>
          <% if pensioner.anexo8?%>
            <td><%= link_to pensioner.anexo2.original_filename, pensioner.anexo2.url, target: '_blank', id:'pdf-link' %></td>
          <% end %>
          <% if pensioner.anexo9?%>
            <td><%= link_to pensioner.anexo2.original_filename, pensioner.anexo2.url, target: '_blank', id:'pdf-link' %></td>
          <% end %>

        <% end %>
      </tr>
    </tbody>
    <% if current_user.role.include?('integrador') or current_user.role.include?('coordinador')%>
      <td><%= link_to 'Editar', edit_pensioner_path(pensioner),class:'btn btn-danger text-white' %></td>
      <td><%= link_to 'Borrar', pensioner, method: :delete, class:'btn btn-secondary text-white' %></td>
    <% end %>
</table>

app/views/pensioners/edit.html.erb
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
      <tr>
        <th scope="col">Turno</th>
        <th scope="col">Número oficio</th>
        <th scope="col">Fecha oficio</th>
        <th scope="col">Fecha recepción</th>
        <th scope="col">Promovente</th>
        <th scope="col">Número juicio</th>
        <th scope="col">Turnado</th>
        <th scope="col">Número correspondencia</th>
        <th scope="col">Anexo</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @pensioner.turno %></td>
        <td><%= @pensioner.numero_oficio %></td>
        <td><%= @pensioner.fecha_oficio %></td>
        <td><%= @pensioner.fecha_recepcion %></td>
        <td><%= @pensioner.promovente %></td>
        <td><%= @pensioner.numero_juicio %></td>
        <td><%= @pensioner.turnado %></td>
        <td><%= @pensioner.numero_correspondencia%></td>
        <td><%= link_to @pensioner.anexo1.original_filename, @pensioner.anexo1.url, target: '_blank', id:'pdf-link' %></td>
      </tr>
    </tbody>
  </table>
  <hr>
  <br>
  <%= render 'form', pensioner: @pensioner %>

app/views/pensioners/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.role == 'secretaria' %>
<div class="resultados"></div>
  <%= form_tag '/search/create', method: :get, remote: true, id: "search-form" do %>
    <%= text_field :keyword, nil, placeholder: 'Buscador'%>
    <%= button_tag :Buscar, class:'btn btn-secondary'%>
  <% end %>
  <%= link_to 'NUEVO REGISTRO', new_pensioner_path, class:'btn btn-success text-white float-right mb-1' %>
<% end %>

<% if current_user.role == 'integrador' %>
  <div class="row">
    <div class="col-md-8">
    <%= form_tag '/search/create', method: :get, remote: true, id: "search-form" do %>
      <%= text_field :keyword, nil, placeholder: 'Buscador', class:'form-control col-md-6'%>
      <br>
      <%= button_tag :Buscar, class:'btn btn-secondary col-md-3'%>
    <% end %>
  </div>
  <div class="col-md-4">
    <div class="float-right">
        <%= link_to "EXPORTAR xlsx", pensioners_path(format: "xlsx"),class:'btn btn-success text-white'%>
    </div>
  </div>
  </div>
  <div class="resultados"></div>
<% end %>
<% if current_user.role == 'coordinador' %>
  <div class="row">
    <div class="col-md-8">
    <%= form_tag '/search/create', method: :get, remote: true, id: "search-form" do %>
      <%= text_field :keyword, nil, placeholder: 'Buscador', class:'form-control col-md-6'%>
      <br>
      <%= button_tag :Buscar, class:'btn btn-secondary col-md-3'%>
    <% end %>
  </div>
  <div class="col-md-4">
    <div class="float-right">
        <%= link_to "EXPORTAR xlsx", pensioners_path(format: "xlsx"),class:'btn btn-success text-white'%>
    </div>
  </div>
  </div>
  <div class="resultados"></div>
<% end %>


<br>

<% if current_user.role.include?('secretaria')%>
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Turno</th>
      <th scope="col">Número oficio</th>
      <th scope="col">Fecha oficio</th>
      <th scope="col">Fecha recepción</th>
      <th scope="col">Promovente</th>
      <th scope="col">Número juicio</th>
      <th scope="col">Turnado</th>
      <th scope="col">Número correspondencia</th>
      <th scope="col">Anexo</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @pensioners.each do |pensioner| %>
      <tr>
        <td><%= pensioner.turno %></td>
        <td><%= pensioner.numero_oficio %></td>
        <td><%= pensioner.fecha_oficio %></td>
        <td><%= pensioner.fecha_recepcion %></td>
        <td><%= pensioner.promovente %></td>
        <td><%= pensioner.numero_juicio %></td>
        <td><%= pensioner.turnado %></td>
        <td><%= pensioner.numero_correspondencia%></td>
        <% if pensioner.anexo1?%>
          <td><%= link_to pensioner.anexo1.original_filename, pensioner.anexo1.url, target: '_blank', id:'pdf-link' %></td>
          <%else%>
          <td></td>
        <% end %>
        <% if pensioner.anexo13?%>
          <td><%= link_to pensioner.anexo13.original_filename, pensioner.anexo13.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if pensioner.anexo14?%>
          <td><%= link_to pensioner.anexo14.original_filename, pensioner.anexo14.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if pensioner.anexo15?%>
          <td><%= link_to pensioner.anexo15.original_filename, pensioner.anexo15.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if pensioner.anexo16?%>
          <td><%= link_to pensioner.anexo16.original_filename, pensioner.anexo16.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if pensioner.anexo17?%>
          <td><%= link_to pensioner.anexo17.original_filename, pensioner.anexo17.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if pensioner.anexo18?%>
          <td><%= link_to pensioner.anexo18.original_filename, pensioner.anexo18.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <td><%= link_to 'Editar', edit_pensioner_path(pensioner),class:'btn btn-secondary text-white' %></td>
        <td><%= link_to 'Mostrar', pensioner_path(pensioner),class:'btn btn-secondary text-white' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<% if current_user.role.include?('secretaria')%>
  <%= will_paginate @pensioners,:previous_label => 'Anterior ' ,:next_label => :Siguiente, class:'paginate text-center' %>
<% end %>

app/views/pensioners/new.html.erb
<h1>Nuevo registro</h1>
<br>
<%= render 'form', pensioner: @pensioner %>

app/views/pensioners/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
  <thead>
    <tr>
      <th scope="col">Turno</th>
      <th scope="col">Numero oficio</th>
      <th scope="col">Fecha oficio</th>
      <th scope="col">Fecha recepcion</th>
      <th scope="col">Nombre promovente</th>
      <th scope="col">Numero juicio</th>
      <th scope="col">Numero correspondencia</th>
      <th scope="col">Numero pensión</th>
      <th scope="col">Sala</th>
      <th scope="col">Tipo expediente</th>
      <th scope="col">Numero expediente</th>
      <th scope="col">Observaciones</th>
      <th scope="col">Letra</th>
      <th scope="col">Termino de la sentencia</th>
      <th scope="col">Envio juridico</th>
      <th scope="col">Monto cheque</th>
      <th scope="col">Ajuste cuota</th>
      <th scope="col">Estatus del expediente</th>
      <th scope="col">Clasificación del expediente</th>
      <th scope="col">Anexos</th>

      <th colspan="3"></th>
    </tr>

  </thead>

    <tbody>
      <tr>
        <td><%= @pensioner.turno %></td>
        <td><%= @pensioner.numero_oficio %></td>
        <td><%= @pensioner.fecha_oficio %></td>
        <td><%= @pensioner.fecha_recepcion %></td>
        <td><%= @pensioner.promovente %></td>
        <td><%= @pensioner.numero_juicio %></td>
        <td><%= @pensioner.numero_correspondencia %></td>
        <td><%= @pensioner.numero_pension %></td>
        <td><%= @pensioner.sala %></td>
        <td><%= @pensioner.tipo_expediente %></td>
        <td><%= @pensioner.numero_expediente %></td>
        <td><%= @pensioner.observaciones %></td>
        <td><%= @pensioner.letra%></td>
        <td><%= @pensioner.termino%></td>
        <td><%= @pensioner.envio_juridico %></td>
        <td><%= @pensioner.monto_cheque %></td>
        <td><%= @pensioner.ajuste_cuota %></td>
        <td><%= @pensioner.estatus_expediente%></td>
        <td><%= @pensioner.clasificacion%></td>
        <% if @pensioner.anexo2?%>
          <td><%= link_to @pensioner.anexo2.original_filename, @pensioner.anexo2.url, target: '_blank', id:'pdf-link' %></td>
          <% else %>
          <td></td>
        <% end %>
        <% if @pensioner.anexo3?%>
          <td><%= link_to @pensioner.anexo3.original_filename, @pensioner.anexo3.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if @pensioner.anexo4?%>
          <td><%= link_to @pensioner.anexo4.original_filename, @pensioner.anexo4.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if @pensioner.anexo5?%>
          <td><%= link_to @pensioner.anexo5.original_filename, @pensioner.anexo5.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if @pensioner.anexo6?%>
          <td><%= link_to @pensioner.anexo6.original_filename, @pensioner.anexo6.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if @pensioner.anexo7?%>
          <td><%= link_to @pensioner.anexo7.original_filename, @pensioner.anexo7.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if @pensioner.anexo8?%>
          <td><%= link_to @pensioner.anexo8.original_filename, @pensioner.anexo8.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>
        <% if @pensioner.anexo9?%>
          <td><%= link_to @pensioner.anexo9.original_filename, @pensioner.anexo9.url, target: '_blank', id:'pdf-link' %></td>
        <% end %>

        <% if current_user.role == 'coordinador' %>
          <tr>
            <th scope="col">Què se liquida</th>
            <th scope="col">Fecha liquidación</th>
            <th scope="col">Autoridad cumplimiento</th>
            <th scope="col">Materia</th>
            <th scope="col">Número UJ</th>
            <th scope="col">Fecha UJ</th>
            <th scope="col">Número SP</th>
            <th scope="col">Fecha SP</th>
            <th scope="col">Fecha sentencia</th>
            <th scope="col">Integrador</th>
            <th scope="col">Liquidador</th>
            <th scope="col">Estatus Final</th>
            <th colspan="3"></th>
          </tr>
          <tr>
            <td><%= @pensioner.que_se_liquida %></td>
            <td><%= @pensioner.fecha_liquidacion %></td>
            <td><%= @pensioner.autoridad_cumplimiento %></td>
            <td><%= @pensioner.materia %></td>
            <td><%= @pensioner.numero_uj %></td>
            <td><%= @pensioner.fecha_uj %></td>
            <td><%= @pensioner.numero_sp %></td>
            <td><%= @pensioner.fecha_sp %></td>
            <td><%= @pensioner.fecha_sentencia %></td>
            <td><%= @pensioner.integrador %></td>
            <td><%= @pensioner.liquidador %></td>
            <td><%= @pensioner.estado_final %></td>
          </tr>
        <% end %>
      </tr>
    </tbody>
  </tbody>
</table>
<%= link_to 'Atras', pensioners_path, class:'btn btn-secondary text-white'%>
<%= link_to 'Editar', edit_pensioner_path(@pensioner), class:'btn btn-danger text-white'%>